# Pipeline | Anomalias e Normalização [Fase 1 - credit_data]

## Importar dados do Drive

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Bibliotecas de Python

In [7]:
!pip -q install plotly
!pip -q install yellowbrick

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

## Importar DataFrame [base_credit] - Descrição da base

In [9]:
base_credit = pd.read_csv('/content/drive/MyDrive/am-t4/credit_data.csv')

In [10]:
base_credit

      clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[2000 rows x 5 columns]

In [11]:
base_credit.describe()

          clientid        income          age          loan      default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

## Análise Exploratória de Anomalias [Alunos]

Possíveis idades negativas - (Incongruencias ou Impossibilidades) | resultante: Normalização

In [12]:
base_credit.loc[base_credit['age'] < 0]

    clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

Possíveis ganhos negativos (Incongruencia ou impossibilidades) | resultante: Nulos

In [13]:
base_credit.loc[base_credit['income'] < 0]

Empty DataFrame
Columns: [clientid, income, age, loan, default]
Index: []

Possíveis nulidades  - (Dados nulos em bases) | resultante: Normalização

In [14]:
base_credit.isnull().sum()

clientid    0
income      0
age         3
loan        0
default     0
dtype: int64

In [16]:
base_credit[base_credit.isnull().any(axis=1)]

    clientid        income  age         loan  default
28        29  59417.805406  NaN  2082.625938        0
30        31  48528.852796  NaN  6155.784670        0
31        32  23526.302555  NaN  2862.010139        0

Possibilidade de Dividade Negativa - (Incongruencia ou Impossibilidade) | resultante: Nula

In [17]:
base_credit.loc[base_credit['loan'] < 0]

Empty DataFrame
Columns: [clientid, income, age, loan, default]
Index: []